language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: NG4ZCZbrsmWIxffJRMPAfIsJGBtUtAzjDAJIfYIjpXcwx5tJOQ2K093yU6tc6fJVUyEbP1LLIQhzC8p8KOL6q8Wa8+oW1vu5aUqllo8idel6ODGbCSXUAYnZLlNV5AnVDsG3y40nWyX4ptRw4/UQbfY92DQNXCYiL00skofNPh+ABHl+wuDaYLDJbZq8HiclDcm0rbejVp7ewsZz0XGqljAIi92ZkIktm8/BO+tw5KQnC1H3lkkFM9yDVvMXITyklmICOynytA9wMrodAKZdsNgl9Tvx+wyXoeSU3bzwmvd0T2O6B+7DiOv6EREU4Wsk/kBhHyeM+bWyhXaRF/88lmTFznLJeX8KYqRFCArsExhCrsAhZyJA0kh2LNVpD79u9L5SfRnVDyz+4MaVnAvanFeId/A4UGyLepDAWWXiyAEwevfu0y5g0Tr417Nd2tXwpjFKBrvPABA/vF0MaUKR0/02G0G1z/4S9eZxsLRr2woxOcFU5B0Ru6mevmJMST6JvMakUZkSupuQWwS+Z3ESGYotlhVT3W6XDn+9c9dRvZiEaklhKTSLERmSrp0x41fjz6Bnaap8pNT+xr4Kb6iI3a+ERWHzIWmURJjh6rplFJEmywsukzDWUcBklSMwOWplyGbXFqYEjMbpE1LBt5DPygT2Vjyd9ERJWPNhCznS7ns=
  app: blog-app-mongoose-challenge
  on:
    repo: steve2482/blog-app-mongoose-challenge-solution
